### ISSUE TITLE
404反馈

### ISSUE THREAD

**Issue by SYCstudio** [konnyakuxzy/BZPRO#1]
我就说前段时间怎么不见了，原来是偷偷更新去了啊orz。  
不过https://konnyakuxzy.github.io/ 还是404呢，催更。

**Comment by konnyakuxzy** [comment]
emmm....
这个里面的话，了解一下[https://konnyakuxzy.github.io/BZPRO](https://konnyakuxzy.github.io/BZPRO)
QvQ
