### ISSUE TITLE
题目中rar与pdf未爬

### ISSUE THREAD

**Issue by Xeonacid** [konnyakuxzy/BZPRO#2]
为了只爬题面而不爬discuss.php之类的，窝用了个很丑的做法qwq
```
wget -m -E -k -A=problem.php?id=$pid.tmp,png,jpg,gif,bmp,pdf,rar,css,js --load-cookies= .....
```

**Comment by konnyakuxzy** [comment]
我试试啊QvQ
（果然有大佬帮忙了）

**Comment by konnyakuxzy** [comment]
emmm...还是不是很好搞啊QAQ，因为实际上你就算这样把pdf下载下来了链接也并没有被转换。。。
QAQ应该还是我太弱了
Orz如果您能帮忙做到下载pdf的话那就好啦～
欢迎您fork一下啥的弄出这个功能Orz
（我真的很懒而且没啥时间QvQ）

**Comment by Xeonacid** [comment]
@konnyakuxzy bzoj非常贴心地rar/pdf都是相对链接，所以说不转换也可以啊😃

**Comment by konnyakuxzy** [comment]
@Xeonacid emmm...
反例：[https://www.lydsy.com/JudgeOnline/problem.php?id=5393](https://www.lydsy.com/JudgeOnline/problem.php?id=5393)
感觉比较麻烦QAQ

**Comment by Xeonacid** [comment]
@konnyakuxzy 实测可用，wget会自动转换成相对链接qwq  
哦对了，我那个命令有个小锅，应该把`-E`去掉或者`-A=problem.php?id=$pid.tmp.html ...`

**Comment by konnyakuxzy** [comment]
@Xeonacid emmm...能不能具体发一个命令粗来？
比如下载id=5393?

**Comment by Xeonacid** [comment]
```wget -m -k -A=problem.php?id=$5393,problem.php?id=5393.tmp,problem.php?id=5393.tmp.html,png,jpg,gif,webp,bmp,pdf,rar,zip,7z,css,js,txt --load-cookies="gugugu" https://www.lydsy.com/JudgeOnline/problem.php?id=5393`

**Comment by Xeonacid** [comment]
@konnyakuxzy `wget -m -k -A=problem.php?id=5393,problem.php?id=5393.tmp,problem.php?id=5393.tmp.html,png,jpg,gif,webp,bmp,pdf,rar,zip,7z,css,js,txt --load-cookies="gugugu" https://www.lydsy.com/JudgeOnline/problem.php?id=5393 && mv ./www.lydsy.com/JudgeOnline/problem.php?id=5393.tmp ./www.lydsy.com/JudgeOnline/5393.html`
（突然发现bzoj还有不少txt的文件。。。

**Comment by konnyakuxzy** [comment]
emmmm...

thx

BZOJ的txt？

能举个栗子咩？QAQ

**Comment by Xeonacid** [comment]
@konnyakuxzy https://www.lydsy.com/JudgeOnline/problem.php?id=4455
虽然说这个txt是题解，但是也是题面的一部分23333
