### ISSUE TITLE
can you add <mata charset="utf-8"  /> in <head> for every html file?

### ISSUE THREAD

**Issue by hehelego** [konnyakuxzy/BZPRO#4]
QAQ,我在clone了这个离线题库后本机使用firefox打开发现乱码...
本机配置 正常的windows10系统, firefox 61.0.2.

您这里的文件使用了utf-8编码,但是没有在head中使用meta标签指定编码,所以firefox按照系统环境使用了gbk编码造成了乱码问题.  虽然可以通过每次手动调节编码来解决或者通过设置 intl.charset.fallback.utf8_for_file这个选项为true来解决但是都比较麻烦.

请问您能否写个脚本为每个html文件在head标签中加入<meta charset='utf-8' />来显式指定编码呢.

**Comment by konnyakuxzy** [comment]
@hehelego 好的，我现在添加
前几天在外地~~度假~~
所以没时间看github...
抱歉咕了这么久QAQ
粟米马森o.o

**Comment by hehelego** [comment]
@konnyakuxzy ,感谢,前排资瓷.

**Comment by konnyakuxzy** [comment]
@hehelego 应该修复啦23333～
已经弄好咯
（顺便更新了一下咕了很久的爬虫，之前我忘记把可以爬doc文档的爬虫放上来了QwQ）
