### ISSUE TITLE
题目“#1972. [Sdoi2010]猪国杀”显示不正确

### ISSUE THREAD

**Issue by ghost** [konnyakuxzy/BZPRO#5]
应当在爬取后检查一遍HTML或特判一下这个题。

**Comment by konnyakuxzy** [comment]
@Noyukira emmmm...
因为不会设置github消息显示相关配置，才看到您这个issue
其实这是个已知的BUG，而且并不打算修改它——它太畸形了
您不难发现rxz的bzojch也有这个问题
我曾经把猪国杀上传到某OJ上，但是数据库存不下那么长的文本
所以我只能说这题真无语
并不打算修改
（不过如果您有什么好的修改建议我会尽力修改的）

**Comment by remmina** [comment]
这个问题即将被修复

然而实际上这题在BZOJ上显示也是不正常的

**Comment by remmina** [comment]
fixed
